-- MySQL Script generated by MySQL Workbench
-- Sat Apr 10 08:31:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `idchave` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `chave_admin` VARCHAR(10) NOT NULL,
  `cnpjcpf` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `empresa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idchave`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `empresa` VARCHAR(45) NOT NULL,
  `conta_fiado` INT NOT NULL,
  `valor` DECIMAL(4) NOT NULL,
  `login_idchave` INT NOT NULL,
  PRIMARY KEY (`idEmpresa`, `Login_idchave`),
  INDEX `fk_Empresa_Login1_idx` (`Login_idchave` ASC) VISIBLE,
  CONSTRAINT `fk_Empresa_Login1`
    FOREIGN KEY (`Login_idchave`)
    REFERENCES `mydb`.`Login` (`idchave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historico` (
  `idHistorico` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NOT NULL,
  `valor` DECIMAL(4) NOT NULL,
  `Login_idchave` INT NOT NULL,
  PRIMARY KEY (`idHistorico`, `Login_idchave`),
  INDEX `fk_Historico_Login1_idx` (`Login_idchave` ASC) VISIBLE,
  CONSTRAINT `fk_Historico_Login1`
    FOREIGN KEY (`Login_idchave`)
    REFERENCES `mydb`.`Login` (`idchave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from `mydb`.`Login`;
# drop database `mydb`;
# ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
